spring:
  application:
    name: valuationdiamond
#
##              google:
##                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
##                token-uri: https://oauth2.googleapis.com/token
##                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
##                user-name-attribute: sub
  jackson:
    date-format = MM/dd/yyyy, hh:mm aa


  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=diamond_valuation_db
    username: sa
    password: Gi@khoi221203
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        use_sql_comments: true

server:
    port: 8080


frontend:
  url: http://localhost:5173/