spring:
  application:
    name: valuationdiamond

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 862578541921-8kkjcjog81k8ohtm41ukq3td3rmanhv9.apps.googleusercontent.com
            client-secret: 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

  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=diamond_valuation_db
    username: sa
    password: Gi@khoi221203
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        use_sql_comments: true

server:
    port: 8080