# version: '3.8'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "Gi@khoi221203"
      ACCEPT_EULA: Y
    ports:
      - 9999:1433
##       docker compose -p swp-valuation-diamond up -d